{
 "title": "CloudNativePG",
 "tags": [ "cloudnativepg" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "operatorNamespace",
    "label": "Operator Namespace",
    "query": {
     "query": "label_values(controller_runtime_webhook_requests_total{webhook=\"/mutate-postgresql-cnpg-io-v1-cluster\"},namespace)"
    }
   },
   { "name": "namespace", "label": "Database Namespace", "query": { "query": "cnpg_collector_up" } },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "cnpg_collector_up{namespace=~\"$namespace\"}"
    }
   },
   {
    "name": "instances",
    "label": "Instances",
    "query": {
     "query": "cnpg_collector_up{namespace=~\"$namespace\",pod=~\"$cluster-([1-9][0-9]*)$\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "x": 0, "y": 0, "w": 3, "h": 8 } },
  { "title": "Health", "type": "text", "gridPos": { "x": 3, "y": 0, "w": 4, "h": 1 } },
  { "title": "Overview", "type": "text", "gridPos": { "x": 7, "y": 0, "w": 17, "h": 1 } },
  {
   "type": "stat",
   "description": "Cluster Replication Health represents the availability of replica servers available to replace the primary in case of a failure.",
   "gridPos": { "x": 3, "y": 1, "w": 4, "h": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max(cnpg_pg_replication_streaming_replicas{namespace=~\"$namespace\", pod=~\"$instances\"}) - sum(cnpg_pg_replication_is_wal_receiver_up{namespace=~\"$namespace\", pod=~\"$instances\"})) + (clamp_max(max(cnpg_pg_replication_streaming_replicas{namespace=~\"$namespace\", pod=~\"$instances\"}), 1) - 1)",
     "legendFormat": "Replication"
    }
   ]
  },
  {
   "title": "Last failover",
   "type": "stat",
   "gridPos": { "x": 7, "y": 1, "w": 3, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cnpg_pg_postmaster_start_time{namespace=~\"$namespace\",pod=~\"$instances\"})*1000"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "stat",
   "gridPos": { "x": 10, "y": 1, "w": 6, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cnpg_pg_replication_lag{namespace=~\"$namespace\",pod=~\"$instances\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "gauge",
   "description": "CPU Utilisation from Requests",
   "gridPos": { "x": 16, "y": 1, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$instances\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\",  namespace=\"$namespace\", resource=\"cpu\", pod=~\"$instances\"})"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "gauge",
   "description": "Memory Utilisation from Requests",
   "gridPos": { "x": 20, "y": 1, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\",container!=\"\", image!=\"\", pod=~\"$instances\"}) / sum(max by(pod) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\", pod=~\"$instances\"}))"
    }
   ]
  },
  {
   "type": "stat",
   "description": "High resource usage (CPU, Memory, DB Connections)",
   "gridPos": { "x": 3, "y": 3, "w": 4, "h": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ namespace=\"$namespace\", pod=~\"$instances\"}) / sum(kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"cpu\", pod=~\"$instances\"}))",
     "legendFormat": "CPU"
    },
    {
     "expr": "(sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\",container!=\"\", image!=\"\", pod=~\"$instances\"}) / sum(max by(pod) (kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", resource=\"memory\", pod=~\"$instances\"})))",
     "legendFormat": "Memory"
    },
    {
     "expr": " (max(sum by (pod) (cnpg_backends_total{namespace=~\"$namespace\", pod=~\"$instances\"}) / sum by (pod) (cnpg_pg_settings_setting{name=\"max_connections\", namespace=~\"$namespace\", pod=~\"$instances\"})))",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "x": 7, "y": 4, "w": 3, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_collector_postgres_version{namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "x": 10, "y": 4, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(cnpg_pg_stat_database_xact_commit{namespace=~\"$namespace\",pod=~\"$instances\"}[$__rate_interval])) + sum(rate(cnpg_pg_stat_database_xact_rollback{namespace=~\"$namespace\",pod=~\"$instances\"}[$__rate_interval]))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Base Backups are considered healthy when there has been at least one base backup in the last 24 hours.",
   "gridPos": { "x": 3, "y": 5, "w": 2, "h": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max({__name__=~\"cnpg_collector_last_available_backup_timestamp|barman_cloud_cloudnative_pg_io_last_available_backup_timestamp\",namespace=\"$namespace\", pod=~\"$instances\"})",
     "legendFormat": "Backups"
    }
   ]
  },
  {
   "type": "stat",
   "description": "WAL is considered Healthy when the last WAL is 0min to 6min old, Delayed when it is less than 15min and Unsynced for >15min. Idle databases with no pending WAL files are shown as Healthy.",
   "gridPos": { "x": 5, "y": 5, "w": 2, "h": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((1 - cnpg_pg_replication_in_recovery{namespace=~\"$namespace\", pod=~\"$instances\"}) * (time() - timestamp(cnpg_pg_stat_archiver_seconds_since_last_archival{namespace=~\"$namespace\", pod=~\"$instances\"}) +\ncnpg_pg_stat_archiver_seconds_since_last_archival{namespace=~\"$namespace\", pod=~\"$instances\"})\n* on(pod, namespace) group_left()\n(cnpg_collector_pg_wal_archive_status{namespace=~\"$namespace\", pod=~\"$instances\", value=\"ready\"} > bool 0))",
     "legendFormat": "WAL"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "x": 16, "y": 5, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\"$instances\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Container memory working set",
   "gridPos": { "x": 20, "y": 5, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$instances\", namespace=\"$namespace\", container!=\"\", image!=\"\"})",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Storage", "type": "text", "gridPos": { "x": 0, "y": 8, "w": 9, "h": 1 } },
  { "title": "Backups", "type": "text", "gridPos": { "x": 9, "y": 8, "w": 15, "h": 1 } },
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "x": 0, "y": 9, "w": 9, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_database_size_bytes{namespace=\"$namespace\", pod=~\"$instances\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Base Backup",
   "type": "stat",
   "description": "Elapsed time since the last successful base backup.",
   "gridPos": { "x": 9, "y": 9, "w": 5, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "-(time() - max({__name__=~\"cnpg_collector_last_available_backup_timestamp|barman_cloud_cloudnative_pg_io_last_available_backup_timestamp\",namespace=\"$namespace\",pod=~\"$instances\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last archived WAL",
   "type": "stat",
   "description": "Computes the time since the last known WAL archival in the primary.\nWe ensure to ignore the metric in the replicas by using (1 - cnpg_pg_replication_in_recovery ) as a multiplicative factor. It will be 0 for replicas, 1 for the primary.",
   "gridPos": { "x": 14, "y": 9, "w": 5, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((1 - cnpg_pg_replication_in_recovery{namespace=~\"$namespace\",pod=~\"$instances\"}) * (time() - timestamp(cnpg_pg_stat_archiver_seconds_since_last_archival{namespace=~\"$namespace\",pod=~\"$instances\"}) +\ncnpg_pg_stat_archiver_seconds_since_last_archival{namespace=~\"$namespace\",pod=~\"$instances\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "First Recoverability Point",
   "type": "stat",
   "gridPos": { "x": 19, "y": 9, "w": 5, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max({__name__=~\"cnpg_collector_first_recoverability_point|barman_cloud_cloudnative_pg_io_first_recoverability_point\",namespace=~\"$namespace\",pod=~\"$instances\"})*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Server Health",
   "type": "row",
   "gridPos": { "x": 0, "y": 12, "w": 24, "h": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Instance",
   "type": "text",
   "gridPos": { "x": 0, "y": 13, "w": 3, "h": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "text",
   "gridPos": { "x": 3, "y": 13, "w": 2, "h": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Clustering / replicas",
   "type": "text",
   "gridPos": { "x": 5, "y": 13, "w": 4, "h": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Zone",
   "type": "text",
   "gridPos": { "x": 9, "y": 13, "w": 2, "h": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "text",
   "gridPos": { "x": 11, "y": 13, "w": 4, "h": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Wraparound",
   "type": "text",
   "gridPos": { "x": 15, "y": 13, "w": 4, "h": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Started",
   "type": "text",
   "gridPos": { "x": 19, "y": 13, "w": 3, "h": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "text",
   "gridPos": { "x": 22, "y": 13, "w": 2, "h": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "x": 0, "y": 14, "w": 3, "h": 3 },
   "repeat": "instances",
   "options": {
    "content": "<table style=\"width:100%; height:100%;border:0px solid black;\">\n  <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \"><p style=\"font-weight: bold;\">$instances</p>\n  </td>\n</table>"
   },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "x": 3, "y": 14, "w": 2, "h": 3 },
   "repeat": "instances",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "x": 5, "y": 14, "w": 2, "h": 3 },
   "repeat": "instances",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - cnpg_pg_replication_in_recovery{namespace=~\"$namespace\",pod=~\"$instances\"} + cnpg_pg_replication_is_wal_receiver_up{namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "x": 7, "y": 14, "w": 2, "h": 3 },
   "repeat": "instances",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_replication_streaming_replicas{namespace=~\"$namespace\", pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "This metric depends on exporting the: `topology.kubernetes.io/zone` label through kube-state-metrics (not enabled by default). Can be added by changing its configuration with:\n\n```yaml\nmetricLabelsAllowlist:\n  - nodes=[topology.kubernetes.io/zone]\n```",
   "gridPos": { "x": 9, "y": 14, "w": 2, "h": 3 },
   "repeat": "instances",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=~\"$namespace\", pod=~\"$instances\"} * on(node,instance) group_left(label_topology_kubernetes_io_zone) kube_node_labels",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "x": 11, "y": 14, "w": 4, "h": 3 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * sum by (pod) (cnpg_backends_total{namespace=~\"$namespace\", pod=~\"$instances\"}) / sum by (pod) (cnpg_pg_settings_setting{name=\"max_connections\", namespace=~\"$namespace\", pod=~\"$instances\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "x": 15, "y": 14, "w": 4, "h": 3 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (pod) (cnpg_pg_database_xid_age{namespace=~\"$namespace\", pod=~\"$instances\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "x": 19, "y": 14, "w": 3, "h": 3 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_pg_postmaster_start_time{namespace=~\"$namespace\", pod=~\"$instances\"}*1000"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "x": 22, "y": 14, "w": 2, "h": 3 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cnpg_collector_postgres_version{namespace=~\"$namespace\", pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "text",
   "gridPos": { "x": 0, "y": 17, "w": 24, "h": 1 },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 18, "w": 24, "h": 6 },
   "repeat": "instances",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (cnpg_backends_total{namespace=~\"$namespace\", pod=~\"$instances\"})",
     "legendFormat": "-"
    }
   ]
  },
  {
   "title": "Configuration",
   "type": "row",
   "gridPos": { "x": 0, "y": 24, "w": 24, "h": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Instance",
     "type": "text",
     "gridPos": { "x": 0, "y": 0, "w": 3, "h": 1 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Max Connections",
     "type": "text",
     "gridPos": { "x": 3, "y": 0, "w": 3, "h": 1 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Shared Buffers",
     "type": "text",
     "gridPos": { "x": 6, "y": 0, "w": 3, "h": 1 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Effective Cache Size",
     "type": "text",
     "gridPos": { "x": 9, "y": 0, "w": 3, "h": 1 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Work Mem",
     "type": "text",
     "gridPos": { "x": 12, "y": 0, "w": 3, "h": 1 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Maintenance Work Mem",
     "type": "text",
     "gridPos": { "x": 15, "y": 0, "w": 3, "h": 1 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Random Page Cost",
     "type": "text",
     "gridPos": { "x": 18, "y": 0, "w": 3, "h": 1 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Sequential Page Cost",
     "type": "text",
     "gridPos": { "x": 21, "y": 0, "w": 3, "h": 1 },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "x": 0, "y": 1, "w": 3, "h": 3 },
     "repeat": "instances",
     "options": {
      "content": "<table style=\"width:100%; height:100%;border:0px solid black;\">\n  <td style=\"text-align: center;vertical-align: middle;border:0px solid black; \"><p style=\"font-weight: bold;\">$instances</p>\n  </td>\n</table>"
     },
     "targets": [
      {
       "expr": "kube_pod_container_status_ready{container=\"postgres\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "x": 3, "y": 1, "w": 3, "h": 3 },
     "repeat": "instances",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cnpg_pg_settings_setting{name=\"max_connections\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "x": 6, "y": 1, "w": 3, "h": 3 },
     "repeat": "instances",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (pod) (cnpg_pg_settings_setting{name=\"shared_buffers\",namespace=~\"$namespace\",pod=~\"$instances\"}) * max by (pod) (cnpg_pg_settings_setting{name=\"block_size\",namespace=~\"$namespace\",pod=~\"$instances\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "x": 9, "y": 1, "w": 3, "h": 3 },
     "repeat": "instances",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (pod) (cnpg_pg_settings_setting{name=\"effective_cache_size\",namespace=~\"$namespace\",pod=~\"$instances\"}) * max by (pod) (cnpg_pg_settings_setting{name=\"block_size\",namespace=~\"$namespace\",pod=~\"$instances\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "x": 12, "y": 1, "w": 3, "h": 3 },
     "repeat": "instances",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cnpg_pg_settings_setting{name=\"work_mem\",namespace=~\"$namespace\",pod=~\"$instances\"} * 1024",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "x": 15, "y": 1, "w": 3, "h": 3 },
     "repeat": "instances",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cnpg_pg_settings_setting{name=\"maintenance_work_mem\",namespace=~\"$namespace\",pod=~\"$instances\"} * 1024",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "x": 18, "y": 1, "w": 3, "h": 3 },
     "repeat": "instances",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cnpg_pg_settings_setting{name=\"random_page_cost\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "x": 21, "y": 1, "w": 3, "h": 3 },
     "repeat": "instances",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cnpg_pg_settings_setting{name=\"seq_page_cost\",namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Configurations",
     "type": "table",
     "gridPos": { "x": 0, "y": 7, "w": 24, "h": 9 },
     "targets": [
      {
       "expr": "cnpg_pg_settings_setting{namespace=~\"$namespace\",pod=~\"$instances\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operational Stats",
   "type": "row",
   "gridPos": { "x": 0, "y": 25, "w": 24, "h": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 26, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$instances\", namespace=~\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (container memory working set)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 26, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$instances\", namespace=\"$namespace\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Session States",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 33, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "sum(cnpg_backends_total{namespace=~\"$namespace\",pod=~\"$instances\"}) by (pod)",
     "legendFormat": "total ({{pod}})"
    },
    {
     "expr": "sum(cnpg_backends_total{namespace=~\"$namespace\",pod=~\"$instances\"}) by (state, pod)",
     "legendFormat": "{{state}} ({{pod}})"
    }
   ]
  },
  {
   "title": "Transactions [5m]",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 41, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(cnpg_pg_stat_database_xact_commit{namespace=~\"$namespace\",pod=~\"$instances\"}[5m])) by (pod)",
     "legendFormat": "committed ({{pod}})"
    },
    {
     "expr": "sum(rate(cnpg_pg_stat_database_xact_rollback{namespace=~\"$namespace\",pod=~\"$instances\"}[5m])) by (pod)",
     "legendFormat": "rolled back ({{pod}})"
    }
   ]
  },
  {
   "title": "Longest Transaction",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 41, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (pod) (cnpg_backends_max_tx_duration_seconds{namespace=~\"$namespace\",pod=~\"$instances\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Deadlocks [5m]",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 49, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(cnpg_pg_stat_database_deadlocks{datname=\"\",namespace=~\"$namespace\",pod=~\"$instances\"}[5m])",
     "legendFormat": "count ({{pod}})"
    }
   ]
  },
  {
   "title": "Blocked Queries",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 49, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "cnpg_backends_waiting_total{namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Write Ahead Log",
   "type": "row",
   "gridPos": { "x": 0, "y": 57, "w": 24, "h": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "WAL Segment Archive Status",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 58, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "cnpg_collector_pg_wal_archive_status{value=\"ready\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "ready ({{pod}})"
    },
    {
     "expr": "cnpg_collector_pg_wal_archive_status{value=\"done\",namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "done ({{pod}})"
    }
   ]
  },
  {
   "title": "WAL Count",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 58, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "cnpg_collector_pg_wal{pod=~\"$instances\", namespace=~\"$namespace\", value=\"count\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Archiver Status [5m]",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 66, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(cnpg_pg_stat_archiver_archived_count{namespace=~\"$namespace\",pod=~\"$instances\"}[5m])",
     "legendFormat": "archived ({{pod}})"
    },
    {
     "expr": "rate(cnpg_pg_stat_archiver_failed_count{namespace=~\"$namespace\",pod=~\"$instances\"}[5m])",
     "legendFormat": "failed ({{pod}})"
    }
   ]
  },
  {
   "title": "Last Archive Age",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 66, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cnpg_pg_stat_archiver_seconds_since_last_archival{namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "age ({{pod}})"
    }
   ]
  },
  {
   "title": "Collector Stats",
   "type": "row",
   "gridPos": { "x": 0, "y": 74, "w": 24, "h": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Collection Duration",
   "type": "heatmap",
   "gridPos": { "x": 0, "y": 75, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "cnpg_collector_collection_duration_seconds{namespace=~\"$namespace\",pod=~\"$instances\"}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 75, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "cnpg_collector_last_collection_error{namespace=~\"$namespace\",pod=~\"$instances\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Backups",
   "type": "row",
   "gridPos": { "x": 0, "y": 83, "w": 24, "h": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "First Recoverability Point",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 84, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "max({__name__=~\"cnpg_collector_first_recoverability_point|barman_cloud_cloudnative_pg_io_first_recoverability_point\",namespace=~\"$namespace\",pod=~\"$instances\"})*1000 > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "row",
   "gridPos": { "x": 0, "y": 92, "w": 24, "h": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requested/Timed",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 93, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate({__name__=~\"cnpg_pg_stat_(bgwriter|checkpointer)_checkpoints_req\",namespace=~\"$namespace\",pod=~\"$instances\"}[$__rate_interval])",
     "legendFormat": "req/{{pod}}"
    },
    {
     "expr": "rate({__name__=~\"cnpg_pg_stat_(bgwriter|checkpointer)_checkpoints_timed\",namespace=~\"$namespace\",pod=~\"$instances\"}[$__rate_interval])",
     "legendFormat": "timed/{{pod}}"
    }
   ]
  },
  {
   "title": "Write/Sync time",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 93, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate({__name__=~\"cnpg_pg_stat_(bgwriter_checkpoint|checkpointer)_write_time\", namespace=~\"$namespace\", pod=~\"$instances\"}[$__rate_interval])",
     "legendFormat": "write/{{pod}}"
    },
    {
     "expr": "rate({__name__=~\"cnpg_pg_stat_(bgwriter_checkpoint|checkpointer)_sync_time\", namespace=~\"$namespace\", pod=~\"$instances\"}[$__rate_interval])",
     "legendFormat": "sync/{{pod}}"
    }
   ]
  },
  { "title": "Extensions", "type": "row", "gridPos": { "x": 0, "y": 101, "w": 24, "h": 1 } },
  {
   "title": "Installed extensions",
   "type": "table",
   "description": "Show the installed extensions and their versions",
   "gridPos": { "x": 0, "y": 102, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "max(cnpg_pg_extensions_update_available{pod=~\"$instances\", namespace=~\"$namespace\"}) by (datname, extname, default_version, installed_version)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}